-- Stone Memory · архітектурний камінь: звірка з ринком слябів (вересень 2026)
-- Згенеровано з data/stone/seed. Виконати в Supabase SQL Editor після stilnytsi-cms-6-ukrainian-first-2026-09.sql. Повторний запуск безпечний.
-- Те саме робить scripts/apply-market-check.ts через REST. Після імпорту деплой або збереження будь-якого запису в адмінці скидає кеш.
begin;

-- 1. 28 колекцій, яких немає в жодного українського продавця слябів (docs/stone-market-check-2026-09.md) → приховати
update public.stilnytsi_materials set hidden = true where slug = 'calacatta-oro';
update public.stilnytsi_materials set hidden = true where slug = 'marmara-white';
update public.stilnytsi_materials set hidden = true where slug = 'mont-blanc';
update public.stilnytsi_materials set hidden = true where slug = 'blue-roma';
update public.stilnytsi_materials set hidden = true where slug = 'fusion-blue';
update public.stilnytsi_materials set hidden = true where slug = 'cristal-tempest';
update public.stilnytsi_materials set hidden = true where slug = 'titanium';
update public.stilnytsi_materials set hidden = true where slug = 'black-java';
update public.stilnytsi_materials set hidden = true where slug = 'tiger-onyx';
update public.stilnytsi_materials set hidden = true where slug = 'himalayan-onyx';
update public.stilnytsi_materials set hidden = true where slug = 'travertino-light-dorato';
update public.stilnytsi_materials set hidden = true where slug = 'travertino-scabas';
update public.stilnytsi_materials set hidden = true where slug = 'travertino-striato-silver';
update public.stilnytsi_materials set hidden = true where slug = 'travertino-ararat';
update public.stilnytsi_materials set hidden = true where slug = 'jerusalem-gold';
update public.stilnytsi_materials set hidden = true where slug = 'jerusalem-grey';
update public.stilnytsi_materials set hidden = true where slug = 'jerusalem-yellow';
update public.stilnytsi_materials set hidden = true where slug = 'nero-belgio';
update public.stilnytsi_materials set hidden = true where slug = 'atlantic-blue';
update public.stilnytsi_materials set hidden = true where slug = 'borriol';
update public.stilnytsi_materials set hidden = true where slug = 'caesarstone-4001-fresh-concrete';
update public.stilnytsi_materials set hidden = true where slug = 'caesarstone-5171-arabetto';
update public.stilnytsi_materials set hidden = true where slug = 'caesarstone-calacatta-nuvo';
update public.stilnytsi_materials set hidden = true where slug = 'laminam-nero-marquina';
update public.stilnytsi_materials set hidden = true where slug = 'neolith-arctic-white';
update public.stilnytsi_materials set hidden = true where slug = 'neolith-calacatta';
update public.stilnytsi_materials set hidden = true where slug = 'neolith-iron-corten';
update public.stilnytsi_materials set hidden = true where slug = 'neolith-estatuario';

-- 2. 24 заміни з наявністю на ринку, приховані до появи фото (docs/stone-photo-import-2026-09.md)
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('vratza-r1', '{"slug":"vratza-r1","name":"Вапняк Vratza R1","material":"marmur","family":"Вапняк","origin":"Болгарія","tone":"світло-бежевий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["фасади","підлога","облицювання"],"description":"Вапняк Vratza R1 — світло-бежевий болгарський камінь із дрібним рівним зерном, найближчий за виглядом до єрусалимського вапняку, але з європейського складу. Фасади, підлоги, облицювання стін; матовий і шліфований фініш.","image":"/materials/vratza-r1.webp","cardImage":"/materials/vratza-r1.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":95,"unit":"м²","currency":"€"},"specs":{"density":"2500","absorption":"2,0","compressive":"70","frost":"50","radiation":"I клас"}}'::jsonb, true, 1100) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('vratza-r3', '{"slug":"vratza-r3","name":"Вапняк Vratza R3","material":"marmur","family":"Вапняк","origin":"Болгарія","tone":"бежевий із мушлями","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["фасади","тераси","облицювання"],"description":"Вапняк Vratza R3 — бежевий болгарський вапняк із помітними мушлями й порами, тепліший і фактурніший за R1. Фасади, тераси, огорожі; після просочення тримає вологу й мороз.","image":"/materials/vratza-r3.webp","cardImage":"/materials/vratza-r3.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":52,"unit":"м²","currency":"€"},"specs":{"density":"2450","absorption":"2,5","compressive":"60","frost":"50","radiation":"I клас"}}'::jsonb, true, 1101) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('travertino-medium', '{"slug":"travertino-medium","name":"Травертин Medium","material":"marmur","family":"Травертин","origin":"Туреччина","tone":"бежевий середнього тону","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["фасади","підлога","ванна"],"description":"Травертин Medium — бежевий турецький камінь середнього тону з дрібними порами, класична заміна італійського Classico. Фасади, підлоги, ванні кімнати з заповненими порами.","image":"/materials/travertino-medium.webp","cardImage":"/materials/travertino-medium.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":95,"unit":"м²","currency":"€"},"specs":{"density":"2450","absorption":"1,5","compressive":"70","frost":"50","radiation":"I клас"}}'::jsonb, true, 1102) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('travertino-alabastrino', '{"slug":"travertino-alabastrino","name":"Травертин Alabastrino","material":"marmur","family":"Травертин","origin":"Італія","tone":"світлий кремовий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["облицювання","підлога","ванна"],"description":"Травертин Alabastrino — світлий кремовий італійський камінь із тонким рівним шаруванням і майже без великих пор. Найсвітліший із травертинів: підлоги, стіни ванних, підвіконня.","image":"/materials/travertino-alabastrino.webp","cardImage":"/materials/travertino-alabastrino.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":270,"unit":"м²","currency":"€"},"specs":{"density":"2500","absorption":"1,2","compressive":"80","frost":"50","radiation":"I клас"}}'::jsonb, true, 1103) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('travertino-safari-brown', '{"slug":"travertino-safari-brown","name":"Травертин Safari Brown","material":"marmur","family":"Травертин","origin":"Туреччина","tone":"коричневий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["фасади","каміни","підлога"],"description":"Травертин Safari Brown — коричневий турецький камінь із теплими смугами від горіхового до пісочного. Каміни, фасадні акценти, підлоги в темних інтер’єрах.","image":"/materials/travertino-safari-brown.webp","cardImage":"/materials/travertino-safari-brown.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":160,"unit":"м²","currency":"€"},"specs":{"density":"2450","absorption":"1,5","compressive":"70","frost":"50","radiation":"I клас"}}'::jsonb, true, 1104) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('le-blanc', '{"slug":"le-blanc","name":"Кварцит Le Blanc","material":"kvarcyt","family":"Кварцит","origin":"Бразилія","tone":"білий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","острови","ванна"],"description":"Кварцит Le Blanc — білий бразильський камінь із ледь помітними сірими хмарками, найчистіший білий серед кварцитів. Твердий і стійкий до кислот: світлі кухні, острови, ванні.","image":"/materials/le-blanc.webp","cardImage":"/materials/le-blanc.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2650","absorption":"0,20","compressive":"230","frost":"100","radiation":"I клас"}}'::jsonb, true, 1105) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('kalahari-blue', '{"slug":"kalahari-blue","name":"Кварцит Kalahari Blue","material":"kvarcyt","family":"Кварцит","origin":"Бразилія","tone":"сіро-блакитний","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","стіни"],"description":"Кварцит Kalahari Blue — сіро-блакитний бразильський камінь із м’якими хвилями й світлими прожилками. Спокійна альтернатива синім кварцитам для стільниць і стінових панелей.","image":"/materials/kalahari-blue.webp","cardImage":"/materials/kalahari-blue.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2650","absorption":"0,25","compressive":"200","frost":"100","radiation":"I клас"}}'::jsonb, true, 1106) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('macaubas-fantasy', '{"slug":"macaubas-fantasy","name":"Кварцит Macaubas Fantasy","material":"kvarcyt","family":"Кварцит","origin":"Бразилія","tone":"сіро-білий у хвилястих смугах","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","панно"],"description":"Кварцит Macaubas Fantasy — сіро-білий камінь із хвилястими смугами, як у White Macaubas, але з рухливішим рисунком. Стільниці, панно й острови, де потрібен виразний природний малюнок.","image":"/materials/macaubas-fantasy.webp","cardImage":"/materials/macaubas-fantasy.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2650","absorption":"0,25","compressive":"200","frost":"100","radiation":"I клас"}}'::jsonb, true, 1107) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('white-pearl', '{"slug":"white-pearl","name":"Кварцит White Pearl","material":"kvarcyt","family":"Кварцит","origin":"Бразилія","tone":"перлинно-білий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","ванна"],"description":"Кварцит White Pearl — перлинно-білий бразильський камінь із дрібним блиском кристалів і ніжними сірими лініями. Стільниці й ванні, добре тримає полірування.","image":"/materials/white-pearl.webp","cardImage":"/materials/white-pearl.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2650","absorption":"0,20","compressive":"220","frost":"100","radiation":"I клас"}}'::jsonb, true, 1108) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('negresco', '{"slug":"negresco","name":"Кварцит Negresco","material":"kvarcyt","family":"Кварцит","origin":"Бразилія","tone":"чорний","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","каміни"],"description":"Кварцит Negresco — чорний бразильський камінь із дрібними світлими вкрапленнями і легким сріблястим мерехтінням. Твердіший за чорний мармур і не боїться кислот: стільниці, каміни, барні стійки.","image":"/materials/negresco.webp","cardImage":"/materials/negresco.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2700","absorption":"0,20","compressive":"240","frost":"100","radiation":"I клас"}}'::jsonb, true, 1109) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('london-grey', '{"slug":"london-grey","name":"Кварцит London Grey","material":"kvarcyt","family":"Кварцит","origin":"Бразилія","tone":"сірий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","підлога"],"description":"Кварцит London Grey — сірий бразильський камінь із рівним тоном і тонкими світлими прожилками. Нейтральний фон для кухонь у сірих і дерев’яних тонах, підлоги.","image":"/materials/london-grey.webp","cardImage":"/materials/london-grey.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2650","absorption":"0,25","compressive":"210","frost":"100","radiation":"I клас"}}'::jsonb, true, 1110) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('calacatta-oriental', '{"slug":"calacatta-oriental","name":"Мармур Calacatta Oriental","material":"marmur","family":"Мармур","origin":"Імпорт","tone":"білий із сірими жилами","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["ванна","стільниці","облицювання"],"description":"Мармур Calacatta Oriental — білий камінь із сірими жилами середньої товщини, доступніша заміна італійської Калакати. Ванні, стільниці під накладну раковину, облицювання стін.","image":"/materials/calacatta-oriental.webp","cardImage":"/materials/calacatta-oriental.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2700","absorption":"0,25","compressive":"110","frost":"50","radiation":"I клас"}}'::jsonb, true, 1111) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('volakas', '{"slug":"volakas","name":"Мармур Volakas","material":"marmur","family":"Мармур","origin":"Греція","tone":"білий із сірими смугами","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["ванна","підлога","підвіконня"],"description":"Мармур Volakas — білий грецький камінь із сірими, подекуди бузковими смугами. Класика для ванних і підлог; слябами є на складах у Києві.","image":"/materials/volakas.webp","cardImage":"/materials/volakas.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":140,"unit":"м²","currency":"€"},"specs":{"density":"2700","absorption":"0,20","compressive":"120","frost":"50","radiation":"I клас"}}'::jsonb, true, 1112) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('honey-onyx', '{"slug":"honey-onyx","name":"Онікс Honey","material":"marmur","family":"Онікс","origin":"Імпорт","tone":"медово-жовтий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["панно","стійки","підсвітка"],"description":"Онікс Honey — медово-жовтий напівпрозорий камінь із шарами від золотистого до світло-коричневого. Підсвічені стійки, панно, ніші; імпортний сляб під замовлення.","image":"/materials/honey-onyx.webp","cardImage":"/materials/honey-onyx.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":700,"unit":"м²","currency":"€"},"specs":{"density":"2650","absorption":"0,20","compressive":"80","frost":"25","radiation":"I клас"}}'::jsonb, true, 1113) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('bianco-a-onyx', '{"slug":"bianco-a-onyx","name":"Онікс Bianco A","material":"marmur","family":"Онікс","origin":"Імпорт","tone":"білий напівпрозорий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["панно","ванна","підсвітка"],"description":"Онікс Bianco A — білий напівпрозорий камінь із м’якими сірими й кремовими хмарами. Найсвітліший онікс для панно, ванн і підсвічених стін; імпортний сляб під замовлення.","image":"/materials/bianco-a-onyx.webp","cardImage":"/materials/bianco-a-onyx.webp","care":"Нейтральний pH, просочення та негайне видалення кислот.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":685,"unit":"м²","currency":"€"},"specs":{"density":"2650","absorption":"0,20","compressive":"80","frost":"25","radiation":"I клас"}}'::jsonb, true, 1114) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('caesarstone-4011-cloudburst-concrete', '{"slug":"caesarstone-4011-cloudburst-concrete","name":"Caesarstone 4011 Cloudburst Concrete","material":"kvarc","family":"Кварц","origin":"Caesarstone","tone":"сірий бетон","finishes":["полірований","матовий"],"thicknesses":[20,30],"applications":["стільниці","острови","підвіконня"],"description":"Caesarstone 4011 Cloudburst Concrete — кварцова поверхня під світлий бетон із ледь помітними хмарками й матовим фінішем. Сучасні кухні й ванні без блиску; не має пор, гаряче — через підставку.","image":"/materials/caesarstone-4011-cloudburst-concrete.webp","cardImage":"/materials/caesarstone-4011-cloudburst-concrete.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,05","compressive":"180","frost":"не для вулиці","radiation":"I клас"},"brand":"Caesarstone"}'::jsonb, true, 1115) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('caesarstone-5143-white-attica', '{"slug":"caesarstone-5143-white-attica","name":"Caesarstone 5143 White Attica","material":"kvarc","family":"Кварц","origin":"Caesarstone","tone":"білий із сірими жилами","finishes":["полірований","матовий"],"thicknesses":[20,30],"applications":["стільниці","острови","підвіконня"],"description":"Caesarstone 5143 White Attica — білий кварц із сірими жилами в дусі мармуру Калаката. Світла кухня з характером мармуру без його чутливості до кислот.","image":"/materials/caesarstone-5143-white-attica.webp","cardImage":"/materials/caesarstone-5143-white-attica.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,05","compressive":"180","frost":"не для вулиці","radiation":"I клас"},"brand":"Caesarstone"}'::jsonb, true, 1116) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('caesarstone-5100-vanilla-noir', '{"slug":"caesarstone-5100-vanilla-noir","name":"Caesarstone 5100 Vanilla Noir","material":"kvarc","family":"Кварц","origin":"Caesarstone","tone":"білий із чорними жилами","finishes":["полірований","матовий"],"thicknesses":[20,30],"applications":["стільниці","острови","підвіконня"],"description":"Caesarstone 5100 Vanilla Noir — білий кварц із тонкими чорними жилами, графічний і контрастний. Острови, стільниці, фартухи в чорно-білих кухнях.","image":"/materials/caesarstone-5100-vanilla-noir.webp","cardImage":"/materials/caesarstone-5100-vanilla-noir.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,05","compressive":"180","frost":"не для вулиці","radiation":"I клас"},"brand":"Caesarstone"}'::jsonb, true, 1117) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('caesarstone-5810-black-tempal', '{"slug":"caesarstone-5810-black-tempal","name":"Caesarstone 5810 Black Tempal","material":"kvarc","family":"Кварц","origin":"Caesarstone","tone":"чорний зі світлими жилами","finishes":["полірований","матовий"],"thicknesses":[20,30],"applications":["стільниці","острови","підвіконня"],"description":"Caesarstone 5810 Black Tempal — чорний кварц зі світлими розводами, як у темного мармуру. Матовий фініш ховає відбитки; стільниці й острови в темних кухнях.","image":"/materials/caesarstone-5810-black-tempal.webp","cardImage":"/materials/caesarstone-5810-black-tempal.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,05","compressive":"180","frost":"не для вулиці","radiation":"I клас"},"brand":"Caesarstone"}'::jsonb, true, 1118) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('neolith-fusion-beton', '{"slug":"neolith-fusion-beton","name":"Neolith Fusion Beton","material":"keramohranit","family":"Керамограніт","origin":"Іспанія","tone":"сірий бетон","finishes":["матовий","полірований"],"thicknesses":[6,12],"applications":["стільниці","фасади","облицювання"],"description":"Neolith Fusion Beton — великоформатний спечений камінь із фактурою сірого бетону. Стільниці, фасади меблів, облицювання без швів; не вбирає, витримує гаряче.","image":"/materials/neolith-fusion-beton.webp","cardImage":"/materials/neolith-fusion-beton.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,1","compressive":"400","frost":"≥ 100","radiation":"I клас"},"brand":"Neolith","formats":["1620×3240"]}'::jsonb, true, 1119) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('neolith-mont-blanc', '{"slug":"neolith-mont-blanc","name":"Neolith Mont Blanc","material":"keramohranit","family":"Керамограніт","origin":"Іспанія","tone":"білий мармуроподібний","finishes":["матовий","полірований"],"thicknesses":[6,12],"applications":["стільниці","фасади","облицювання"],"description":"Neolith Mont Blanc — спечений камінь із декором білого мармуру з м’якими сірими жилами. Стільниці, стіни, фасади меблів; шовковистий фініш.","image":"/materials/neolith-mont-blanc.webp","cardImage":"/materials/neolith-mont-blanc.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,1","compressive":"400","frost":"≥ 100","radiation":"I клас"},"brand":"Neolith","formats":["1620×3240"]}'::jsonb, true, 1120) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('neolith-steel-sofia-cuprum', '{"slug":"neolith-steel-sofia-cuprum","name":"Neolith Steel Sofia Cuprum","material":"keramohranit","family":"Керамограніт","origin":"Іспанія","tone":"мідно-іржавий метал","finishes":["матовий","полірований"],"thicknesses":[6,12],"applications":["стільниці","фасади","облицювання"],"description":"Neolith Steel Sofia Cuprum — спечений камінь із фактурою окисленої міді й іржавого металу. Акцентні фасади меблів, барні стійки, стіни в лофтах; заміна Iron Corten.","image":"/materials/neolith-steel-sofia-cuprum.webp","cardImage":"/materials/neolith-steel-sofia-cuprum.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,1","compressive":"400","frost":"≥ 100","radiation":"I клас"},"brand":"Neolith","formats":["1620×3240"]}'::jsonb, true, 1121) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('neolith-classtone-whitesands', '{"slug":"neolith-classtone-whitesands","name":"Neolith ClasStone WhiteSands","material":"keramohranit","family":"Керамограніт","origin":"Іспанія","tone":"світлий пісочний","finishes":["матовий","полірований"],"thicknesses":[6,12],"applications":["стільниці","фасади","облицювання"],"description":"Neolith ClasStone WhiteSands — світлий пісочний спечений камінь із дрібним природним зерном. Спокійна стільниця для теплих інтер’єрів, підходить і для вулиці.","image":"/materials/neolith-classtone-whitesands.webp","cardImage":"/materials/neolith-classtone-whitesands.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,1","compressive":"400","frost":"≥ 100","radiation":"I клас"},"brand":"Neolith","formats":["1620×3240"]}'::jsonb, true, 1122) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('laminam-calce-nero', '{"slug":"laminam-calce-nero","name":"Laminam Calce Nero","material":"keramohranit","family":"Керамограніт","origin":"Італія","tone":"чорний матовий","finishes":["матовий","полірований"],"thicknesses":[6,12],"applications":["стільниці","фасади","облицювання"],"description":"Laminam Calce Nero — чорний матовий керамограніт великого формату з фактурою вапняної штукатурки. Стільниці, фасади меблів, облицювання; заміна декору Nero Marquina.","image":"/materials/laminam-calce-nero.webp","cardImage":"/materials/laminam-calce-nero.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2400","absorption":"≤ 0,1","compressive":"400","frost":"≥ 100","radiation":"I клас"},"brand":"Laminam","formats":["1620×3240"]}'::jsonb, true, 1123) on conflict (slug) do nothing;
commit;
