-- Stone Memory · архітектурний камінь: українське наперед (вересень 2026)
-- Згенеровано з data/stone/seed. Виконати в Supabase SQL Editor після stilnytsi-cms-5-specs-2026-09.sql. Повторний запуск безпечний.
-- Те саме робить scripts/apply-ukrainian-first.ts через REST. Після імпорту зберегти будь-який запис в адмінці, щоб скинути кеш.
begin;

-- 1. Іран і Мексика → «Імпорт»: онікси Onice Bianco, Miele, Verde, Nuvolato, Rainbow і травертин Gold (в останнього ще й опис без «іранський»)
update public.stilnytsi_materials set data = data || jsonb_build_object('origin', 'Імпорт') where slug = 'onice-bianco';
update public.stilnytsi_materials set data = data || jsonb_build_object('origin', 'Імпорт') where slug = 'onice-miele';
update public.stilnytsi_materials set data = data || jsonb_build_object('origin', 'Імпорт') where slug = 'onice-verde';
update public.stilnytsi_materials set data = data || jsonb_build_object('origin', 'Імпорт') where slug = 'onice-nuvolato';
update public.stilnytsi_materials set data = data || jsonb_build_object('origin', 'Імпорт') where slug = 'rainbow-onyx';
update public.stilnytsi_materials set data = data || jsonb_build_object('origin', 'Імпорт', 'description', 'Травертин Gold — золотисто-жовтий камінь із виразними теплими смугами. Яскравий фасад або підлога; імпортний сляб під замовлення.') where slug = 'travertino-gold';

-- 2. Габро й базальт стають окремими родинами (були всередині «Граніт»)
update public.stilnytsi_materials set data = data || jsonb_build_object('family', 'Габро') where slug = 'kometa-black';
update public.stilnytsi_materials set data = data || jsonb_build_object('family', 'Габро') where slug = 'holovynske';
update public.stilnytsi_materials set data = data || jsonb_build_object('family', 'Габро') where slug = 'bukynske';
update public.stilnytsi_materials set data = data || jsonb_build_object('family', 'Габро') where slug = 'antik-nero';
update public.stilnytsi_materials set data = data || jsonb_build_object('family', 'Базальт') where slug = 'berestovetskyi';
update public.stilnytsi_materials set data = data || jsonb_build_object('family', 'Базальт') where slug = 'kostopilskyi';
update public.stilnytsi_materials set data = data || jsonb_build_object('family', 'Базальт') where slug = 'khustovskyi';

-- 3. 14 нових українських колекцій, приховані до появи фото (docs/stone-photo-ukrainian-2026-09.md)
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('chovnovske', '{"slug":"chovnovske","name":"Човновський граніт (Chovnovske)","material":"granit","family":"Граніт","origin":"Житомирська область, Україна","tone":"темно-зелений","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","сходи","фасади"],"description":"Човновський граніт (Chovnovske) — темно-зелений камінь із Житомирщини з дрібним рівним зерном. Рідкісний для України глибокий зелений тон: стільниці й сходи в спокійних інтер’єрах, фасадні вставки.","image":"/materials/chovnovske.webp","cardImage":"/materials/chovnovske.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2700","absorption":"0,20–0,50","compressive":"90–120","frost":"200","radiation":"I клас"}}'::jsonb, true, 1000) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('rogovske', '{"slug":"rogovske","name":"Рогівський граніт (Rogovske)","material":"granit","family":"Граніт","origin":"Житомирська область, Україна","tone":"сіро-зелений","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","сходи","фасади","бруківка"],"description":"Рогівський граніт (Rogovske) — сіро-зелений щільний камінь із Житомирської області, один із найміцніших на стиск серед українських гранітів. Витримує інтенсивний рух: сходи, бруківка, підлоги громадських будівель.","image":"/materials/rogovske.webp","cardImage":"/materials/rogovske.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2710","absorption":"0,18","compressive":"220–255","frost":"300","radiation":"I клас"}}'::jsonb, true, 1001) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('zhadani', '{"slug":"zhadani","name":"Жаданівський граніт (Zhadani)","material":"granit","family":"Граніт","origin":"Житомирська область, Україна","tone":"коричневий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","сходи","фасади"],"description":"Жаданівський граніт (Zhadani) — коричневий камінь із теплим рівним тоном і низьким водопоглинанням. Стільниці під дерев’яні фасади, сходи, фасадні цоколі.","image":"/materials/zhadani.webp","cardImage":"/materials/zhadani.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2710","absorption":"0,16","compressive":"230","frost":"300","radiation":"I клас"}}'::jsonb, true, 1002) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('rosa-raveno', '{"slug":"rosa-raveno","name":"Жадьківський граніт (Rosa Raveno)","material":"granit","family":"Граніт","origin":"Рівненська область, Україна","tone":"коричнево-рожевий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","сходи","фасади"],"description":"Жадьківський граніт (Rosa Raveno) — коричнево-рожевий камінь із Корецького родовища на Рівненщині, з великим кристалічним рисунком. Помітний акцент на стільниці чи сходах, добре виглядає в термообробленому фініші на терасах.","image":"/materials/rosa-raveno.webp","cardImage":"/materials/rosa-raveno.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2730","absorption":"0,08–0,20","compressive":"190–270","frost":"300","radiation":"I клас"}}'::jsonb, true, 1003) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('granat', '{"slug":"granat","name":"Крутнівський граніт (Granat)","material":"granit","family":"Граніт","origin":"Житомирська область, Україна","tone":"рожевий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","сходи","фасади"],"description":"Крутнівський граніт (Granat) — рожевий камінь із насиченими вкрапленнями кольору гранату. Теплий і світлий, для стільниць і підвіконь у класичних інтер’єрах.","image":"/materials/granat.webp","cardImage":"/materials/granat.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2650","absorption":"0,27","compressive":"93","frost":"200","radiation":"I клас"}}'::jsonb, true, 1004) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('dmytrit', '{"slug":"dmytrit","name":"Юр’ївський граніт (Dmytrit)","material":"granit","family":"Граніт","origin":"Житомирська область, Україна","tone":"рожево-сірий","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","підвіконня","фасади"],"description":"Юр’ївський граніт (Dmytrit) — рожево-сірий дрібнозернистий камінь із Житомирщини з одним із найнижчих показників стирання серед українських гранітів. Підвіконня, сходи, фасади.","image":"/materials/dmytrit.webp","cardImage":"/materials/dmytrit.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2650","absorption":"0,16–0,40","compressive":"117","frost":"200","radiation":"I клас"}}'::jsonb, true, 1005) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('voinivske', '{"slug":"voinivske","name":"Войнівський граніт (Rosso Santiago)","material":"granit","family":"Граніт","origin":"Кіровоградська область, Україна","tone":"червоний","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","сходи","фасади","бруківка"],"description":"Войнівський граніт (Rosso Santiago) — червоний камінь Кіровоградщини, близький за тоном до Капустинського, але з дрібнішим зерном. Бруківка, сходи, фасади й стільниці, де потрібен насичений червоний.","image":"/materials/voinivske.webp","cardImage":"/materials/voinivske.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2650","absorption":"0,23","compressive":"93","frost":"200","radiation":"I клас"}}'::jsonb, true, 1006) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('rakhni-polivsky', '{"slug":"rakhni-polivsky","name":"Рахни-Полівський граніт (Rakhni-Polivsky)","material":"granit","family":"Граніт","origin":"Вінницька область, Україна","tone":"чорний","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","каміни","фасади"],"description":"Рахни-Полівський граніт (Rakhni-Polivsky) — чорний дрібнозернистий камінь із Вінниччини. Альтернатива габро для стільниць і камінів: після полірування рівний темний тон, у шліфованому фініші — глибокий графіт.","image":"/materials/rakhni-polivsky.webp","cardImage":"/materials/rakhni-polivsky.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2770","absorption":"0,20","compressive":"150–250","frost":"250","radiation":"I клас"}}'::jsonb, true, 1007) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('galactic-blue', '{"slug":"galactic-blue","name":"Очеретянський лабрадорит (Galactic Blue)","material":"granit","family":"Лабрадорит","origin":"Житомирська область, Україна","tone":"чорний із синім переливом","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","каміни","фасади"],"description":"Очеретянський лабрадорит (Galactic Blue) — чорний камінь із великими кристалами, що спалахують синім. Один із найяскравіших українських лабрадоритів: акцентні стільниці, каміни, фасадні панно.","image":"/materials/galactic-blue.webp","cardImage":"/materials/galactic-blue.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2750–2840","absorption":"0,18–0,21","compressive":"160–170","frost":"250","radiation":"I клас"}}'::jsonb, true, 1008) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('silver-grey', '{"slug":"silver-grey","name":"Ковалівський лабрадорит (Silver Grey)","material":"granit","family":"Лабрадорит","origin":"Житомирська область, Україна","tone":"сіро-чорний","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","каміни","фасади"],"description":"Ковалівський лабрадорит (Silver Grey) — сіро-чорний камінь із сріблястими переливами замість синіх. Стриманіший за Volga Blue, з дуже низьким водопоглинанням: стільниці, сходи, фасади.","image":"/materials/silver-grey.webp","cardImage":"/materials/silver-grey.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2720–2740","absorption":"0,02–0,08","compressive":"180–220","frost":"300","radiation":"I клас"}}'::jsonb, true, 1009) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('fantasy-azure', '{"slug":"fantasy-azure","name":"Слобідський лабрадорит (Fantasy Azure)","material":"granit","family":"Лабрадорит","origin":"Житомирська область, Україна","tone":"чорно-синій","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","каміни","фасади"],"description":"Слобідський лабрадорит (Fantasy Azure) — чорно-синій камінь із Житомирщини з рівномірно розсіяними синіми відблисками. Стільниці, каміни, облицювання стін із підсвіткою.","image":"/materials/fantasy-azure.webp","cardImage":"/materials/fantasy-azure.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2700–2830","absorption":"0,05–0,29","compressive":"160–180","frost":"250","radiation":"I клас"}}'::jsonb, true, 1010) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('lukovetskyi', '{"slug":"lukovetskyi","name":"Луковецький анортозит (Lukovetskiy)","material":"granit","family":"Лабрадорит","origin":"Житомирська область, Україна","tone":"сіро-зелений","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["стільниці","сходи","фасади"],"description":"Луковецький анортозит (Lukovetskiy) — сіро-зелений камінь, споріднений із лабрадоритом, але без сильної іризації: рівний тон із дрібними світлими кристалами. Сходи, фасади, стільниці для спокійних інтер’єрів.","image":"/materials/lukovetskyi.webp","cardImage":"/materials/lukovetskyi.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2670–2930","absorption":"0,04–0,16","compressive":"130–150","frost":"250","radiation":"I клас"}}'::jsonb, true, 1011) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('ovrutskyi', '{"slug":"ovrutskyi","name":"Овруцький кварцит","material":"kvarcyt","family":"Кварцит","origin":"Житомирська область, Україна","tone":"рожево-червоний","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["бруківка","фасади","сходи"],"description":"Овруцький кварцит — рожево-червоний камінь Словечансько-Овруцького кряжу на Житомирщині, з якого викладали бруківку й облицьовували будівлі ще в княжі часи. Дуже твердий і морозостійкий: бруківка, сходи, цоколі, фасадні вставки.","image":"/materials/ovrutskyi.webp","cardImage":"/materials/ovrutskyi.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2600–2650","absorption":"0,10–0,30","compressive":"200–300","frost":"100","radiation":"I клас"}}'::jsonb, true, 1012) on conflict (slug) do nothing;
insert into public.stilnytsi_materials (slug, data, hidden, position) values ('terebovlianskyi', '{"slug":"terebovlianskyi","name":"Теребовлянський пісковик","material":"granit","family":"Пісковик","origin":"Тернопільська область, Україна","tone":"сіро-зелений","finishes":["полірований","шліфований"],"thicknesses":[20,30],"applications":["фасади","облицювання","бруківка"],"description":"Теребовлянський пісковик — сіро-зелений камінь із Тернопільщини з природним сколом і теплим матовим тоном. Традиційний матеріал Поділля для фасадів, огорож і доріжок; для кухонних стільниць не використовується.","image":"/materials/terebovlianskyi.webp","cardImage":"/materials/terebovlianskyi.webp","care":"Нейтральний засіб; для природного каменю перевіряти просочення.","relatedArticles":["yak-vybraty-kamin-dlya-kukhni","yak-doglyadaty-za-granitnoyu-stilnytseyu"],"relatedCategories":["stilnytsi","fasady"],"price":{"value":0,"unit":"м²","currency":"грн"},"specs":{"density":"2300–2500","absorption":"2–4","compressive":"60–100","frost":"50","radiation":"I клас"}}'::jsonb, true, 1013) on conflict (slug) do nothing;
commit;
